modLoader="javafml"
loaderVersion="[35,)"
license="CC0-2.0"
[[mods]]
modId="zawa" #mandatory
version="${file.jarVersion}"
displayName="ZAWA: whatarewenamingitthistime" #mandatory
displayURL="http://zawamod.org/"
description='''

'''
[[dependencies.zawa]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
